import days.*

fun main() {
    println("Day 1:")
    println(day1part1())
    println(day1part2())
    println("Day 2:")
    println(day2Part1())
    println(day2part2())
    println("Day 3:")
    println(day3part1())
    println(day3part2())
    println("Day 4:")
    println(day4part1())
    println(day4part2())
    println("Day 5:")
    println(day5part1())
    println(day5part2())
    println("Day 6:")
    println(day6part1())
    println(day6part2())
    println("Day 7:")
    println(day7part1())
    println(day7part2())
    println("Day 8:")
    println(day8part1())
    println(day8part2())
    println("Day 9:")
    println(day9part1())
}